name: HolyFreeze
version: 1.0
main: ru.nezxenka.holyfreeze.HolyFreeze
api-version: 1.16
depend:
  - PlaceholderAPI
softdepend:
  - Multiverse-Core
loadbefore:
  - ChatPlaytime
load: POSTWORLD
commands:
  freezing:
    aliases:
      - freeze
    permission: holyfreeze.use
  afkstaff:
    permission: holyfreeze.use
  prova:
    permission: holyfreeze.use